//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Run
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Distance { get; set; }
        public Nullable<int> Shoes { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual Shoes Shoes1 { get; set; }
    }
}
