//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShoesEntities : DbContext
    {
        public ShoesEntities()
            : base("name=ShoesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Run> Run { get; set; }
        public virtual DbSet<Shoes> Shoes { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    
        public virtual ObjectResult<SP_SelectAllRuns_WithShouesName_Result> SP_SelectAllRuns_WithShouesName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAllRuns_WithShouesName_Result>("SP_SelectAllRuns_WithShouesName");
        }
    
        public virtual ObjectResult<SP_SelectAllShoesToShoesPanel_Result> SP_SelectAllShoesToShoesPanel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAllShoesToShoesPanel_Result>("SP_SelectAllShoesToShoesPanel");
        }
    
        public virtual ObjectResult<SP_SelectAllShoes_Result> SP_SelectAllShoes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SelectAllShoes_Result>("SP_SelectAllShoes");
        }
    
        public virtual int SP_AddNewRun(Nullable<System.DateTime> date, Nullable<int> distance, Nullable<int> shoes, Nullable<System.TimeSpan> time)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("distance", distance) :
                new ObjectParameter("distance", typeof(int));
    
            var shoesParameter = shoes.HasValue ?
                new ObjectParameter("shoes", shoes) :
                new ObjectParameter("shoes", typeof(int));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AddNewRun", dateParameter, distanceParameter, shoesParameter, timeParameter);
        }
    }
}
