//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string TEST { get; set; }
    }
}
